# Generated by Django 5.0.4 on 2024-04-30 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0008_alter_attendances_punch_alter_attendances_status_and_more'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.FloatField()),
                ('overtime_salary', models.FloatField()),
                ('bonuses', models.FloatField()),
                ('total_compensation', models.FloatField()),
                ('total_deductions', models.FloatField()),
                ('total_salary', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biometrics.employee')),
            ],
        ),
    ]
