# Generated by Django 5.0.4 on 2024-05-05 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0013_employee_is_regular'),
        ('hr', '0003_remove_salary_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payrolls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('basic_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meal_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('overtime_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_present_days', models.IntegerField()),
                ('num_overtime_hr', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tardiness_deduct', models.DecimalField(decimal_places=2, max_digits=10)),
                ('leave_without_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sss_contrib', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('philhealth_contrib', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pagibig_contrib', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('num_tardinesstime_min', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biometrics.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
