# Generated by Django 5.0.4 on 2024-05-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_payrolls_delete_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrolls',
            name='additional_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrolls',
            name='leave_without_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
