# Generated by Django 5.0.4 on 2024-05-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_payrolls_additional_pay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrolls',
            name='num_tardinesstime_min',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
