# Generated by Django 5.0.4 on 2024-05-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_payrolls_num_tardinesstime_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolls',
            name='num_undertime_hr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payrolls',
            name='undertime_deduct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrolls',
            name='weekend_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrolls',
            name='weekend_work_hr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='payrolls',
            name='tardiness_deduct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
