# Generated by Django 5.0.4 on 2024-05-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_payrolls_num_undertime_hr_payrolls_undertime_deduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='NonWorkingDays',
        ),
    ]
