# Generated by Django 5.0.4 on 2024-05-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_events_delete_nonworkingdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
