# Generated by Django 5.0.4 on 2024-04-25 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0002_alter_employee_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendances',
            old_name='employee',
            new_name='employee_id',
        ),
    ]
