# Generated by Django 5.0.4 on 2024-04-25 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0003_rename_employee_attendances_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendances',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
