# Generated by Django 5.0.4 on 2024-04-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0004_rename_employee_id_attendances_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='dv_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='user_id',
            new_name='dv_user_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='civil_status',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='data_hired',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile_number',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='name_suffix',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
