# Generated by Django 5.0.4 on 2024-04-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0005_rename_name_employee_dv_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birthplace',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
