# Generated by Django 5.0.4 on 2024-04-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0007_rename_data_hired_employee_date_hired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendances',
            name='punch',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='attendances',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='attendances',
            name='uid',
            field=models.BigIntegerField(null=True),
        ),
    ]
