# Generated by Django 5.0.4 on 2024-04-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0008_alter_attendances_punch_alter_attendances_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='base_monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
