# Generated by Django 5.0.4 on 2024-05-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0009_employee_base_monthly_salary_employee_is_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='full_attendance',
            field=models.BooleanField(default=False),
        ),
    ]
