# Generated by Django 5.0.4 on 2024-05-03 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0010_employee_full_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='full_attendance',
            new_name='perfect_attendance',
        ),
    ]
