# Generated by Django 5.0.4 on 2024-05-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0012_rename_perfect_attendance_employee_is_perfect_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_regular',
            field=models.BooleanField(default=False),
        ),
    ]
