# Generated by Django 5.0.4 on 2024-05-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0013_employee_is_regular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=60, null=True)),
                ('device_name', models.CharField(max_length=60, null=True)),
                ('ip_address', models.CharField(max_length=50)),
                ('port', models.IntegerField()),
            ],
        ),
    ]
