# Generated by Django 5.0.6 on 2024-05-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0015_device_created_at_device_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendances',
            name='overtime',
            field=models.BooleanField(default=False),
        ),
    ]
